# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Opis')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_deadline', models.DateField(default=None)),
                ('status', models.CharField(choices=[('TD', 'Aktywny'), ('DN', 'Wykonane')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('time_expected', models.IntegerField(default=15)),
                ('difficulty', models.IntegerField(choices=[(1, 'Od ręki'), (3, 'Prosty'), (5, 'Średnie'), (8, 'Trudne'), (13, 'Bardzo trudne')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Category')),
            ],
            options={
                'verbose_name': 'zadanie',
                'verbose_name_plural': 'zadania',
            },
        ),
    ]
