# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180702_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TD', 'Aktywny'), ('DN', 'Wykonane')], max_length=2),
        ),
    ]
